spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/appointment_scheduler_dev"
    username: "postgres"
    password: "bar_brothers"
    driver-class-name: "org.postgresql.Driver"
server:
  error:
    include-message: always
    include-binding-errors: always
